# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ModYSim-GUI.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from mplwidget import MplWidget
from PyQt5.QtGui import QIcon



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1400, 647)
        MainWindow.setWindowTitle("Modelado y Simulación")
        MainWindow.setStyleSheet("background-color: rgb(240, 240, 240);")
        MainWindow.setWindowIcon(QIcon('icon.ico'))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox_metodos = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_metodos.setGeometry(QtCore.QRect(180, 140, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.comboBox_metodos.setFont(font)
        self.comboBox_metodos.setObjectName("comboBox_metodos")
        self.comboBox_metodos.addItem("")
        self.comboBox_metodos.addItem("")
        self.comboBox_metodos.addItem("")
        self.label_seleccionMetodo = QtWidgets.QLabel(self.centralwidget)
        self.label_seleccionMetodo.setGeometry(QtCore.QRect(10, 140, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_seleccionMetodo.setFont(font)
        self.label_seleccionMetodo.setObjectName("label_seleccionMetodo")
        self.lineEdit_input = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_input.setGeometry(QtCore.QRect(90, 70, 331, 31))
        self.lineEdit_input.setText("")
        self.lineEdit_input.setObjectName("lineEdit_input")
        self.label_dxdt = QtWidgets.QLabel(self.centralwidget)
        self.label_dxdt.setGeometry(QtCore.QRect(10, 60, 71, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_dxdt.setFont(font)
        self.label_dxdt.setObjectName("label_dxdt")
        self.label_parametros = QtWidgets.QLabel(self.centralwidget)
        self.label_parametros.setGeometry(QtCore.QRect(10, 210, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_parametros.setFont(font)
        self.label_parametros.setObjectName("label_parametros")
        self.label_ti = QtWidgets.QLabel(self.centralwidget)
        self.label_ti.setGeometry(QtCore.QRect(10, 260, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_ti.setFont(font)
        self.label_ti.setObjectName("label_ti")
        self.label_tf = QtWidgets.QLabel(self.centralwidget)
        self.label_tf.setGeometry(QtCore.QRect(10, 310, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_tf.setFont(font)
        self.label_tf.setObjectName("label_tf")
        self.label_xi = QtWidgets.QLabel(self.centralwidget)
        self.label_xi.setGeometry(QtCore.QRect(10, 360, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_xi.setFont(font)
        self.label_xi.setObjectName("label_xi")
        self.label_h = QtWidgets.QLabel(self.centralwidget)
        self.label_h.setGeometry(QtCore.QRect(10, 410, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_h.setFont(font)
        self.label_h.setObjectName("label_h")
        self.lineEdit_ti = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ti.setGeometry(QtCore.QRect(100, 260, 91, 31))
        self.lineEdit_ti.setText("")
        self.lineEdit_ti.setObjectName("lineEdit_ti")
        self.lineEdit_tf = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_tf.setGeometry(QtCore.QRect(100, 310, 91, 31))
        self.lineEdit_tf.setText("")
        self.lineEdit_tf.setObjectName("lineEdit_tf")
        self.lineEdit_xi = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_xi.setGeometry(QtCore.QRect(100, 360, 91, 31))
        self.lineEdit_xi.setText("")
        self.lineEdit_xi.setObjectName("lineEdit_xi")
        self.lineEdit_h = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_h.setGeometry(QtCore.QRect(150, 410, 91, 31))
        self.lineEdit_h.setText("")
        self.lineEdit_h.setObjectName("lineEdit_h")
        self.pushButton_graficar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_graficar.setGeometry(QtCore.QRect(130, 510, 171, 41))
        self.pushButton_graficar.clicked.connect(self.clickMetodo)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.pushButton_graficar.setFont(font)
        self.pushButton_graficar.setObjectName("pushButton_graficar")
        self.label_titulo = QtWidgets.QLabel(self.centralwidget)
        self.label_titulo.setGeometry(QtCore.QRect(10, 0, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setUnderline(False)
        self.label_titulo.setFont(font)
        self.label_titulo.setObjectName("label_titulo")
        self.MplWidget = MplWidget(self.centralwidget)
        self.MplWidget.setGeometry(QtCore.QRect(450, 40, 900, 551))
        self.MplWidget.setObjectName("MplWidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1118, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.label_author = QtWidgets.QLabel(self.centralwidget)
        self.label_author.setGeometry(QtCore.QRect(10, 600, 1000, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.comboBox_metodos.setItemText(0, _translate("MainWindow", "Euler"))
        self.comboBox_metodos.setItemText(1, _translate("MainWindow", "Euler mejorado"))
        self.comboBox_metodos.setItemText(2, _translate("MainWindow", "Runge-Kutta"))
        self.label_seleccionMetodo.setText(_translate("MainWindow", "Método numerico"))
        self.label_dxdt.setText(_translate("MainWindow", "dx/dt ="))
        self.label_parametros.setText(_translate("MainWindow", "Parámetros:"))
        self.label_ti.setText(_translate("MainWindow", "t inicial ="))
        self.label_tf.setText(_translate("MainWindow", "t final ="))
        self.label_xi.setText(_translate("MainWindow", "x inicial ="))
        self.label_h.setText(_translate("MainWindow", "h (incremento) ="))
        self.pushButton_graficar.setText(_translate("MainWindow", "Graficar"))
        self.label_titulo.setText(_translate("MainWindow", "Problemas de valor inicial"))
        self.label_author.setText(_translate("MainWindow", "Autores: Gastón Ceccotti Espeche, Florencia de la Rasilla Siri, Agustina Diaz, Julian Fernández Santos, Facundo Montesanto"))

    def clickMetodo(self):
        self.funcion = self.lineEdit_input.text()
        self.xi = float(self.lineEdit_xi.text())
        self.ti = float(self.lineEdit_ti.text())
        self.tf = float(self.lineEdit_tf.text())
        self.h = float(self.lineEdit_h.text())
        self.MplWidget.recalculateData(self.comboBox_metodos.currentIndex(), self.funcion, self.xi, self.ti, self.tf, self.h)
        """if (self.comboBox_metodos.currentIndex() == 0):
            euler(self.xi,self.ti,self.tf,self.h, self.funcion)
        if (self.comboBox_metodos.currentIndex() == 1):
            euler_mejorado(self.xi,self.ti,self.tf,self.h, self.funcion)
        if (self.comboBox_metodos.currentIndex() == 2):
            rungeKutta(self.xi,self.ti,self.tf,self.h, self.funcion)"""



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
